apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataservice
  namespace: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataservice
  template:
    metadata:
      labels:
        app: dataservice
    spec:
      containers:
        - name: dataservice
          image: praveen581348/dataservice:14
          ports:
            - containerPort: 8013
          env:
            - name: FLASK_ENV
              value: "production"
