apiVersion: v1
kind: Service
metadata:
  name: dataservice-service
  namespace: data
spec:
  selector:
    app: dataservice
  ports:
    - protocol: TCP
      port: 8013
      targetPort: 8013
      nodePort: 30103
  type: NodePort
